In [5]:
import numpy as np

def gaussian(A, b):
    # Преобразую входные данные в тип float для точности вычислений
    A = A.astype(float)
    b = b.astype(float)
    
    # Определяю размерность матрицы
    n = len(b)

    # Прямой ход метода Гаусса
    for i in range(n):
        max_index = i
        # Находим максимальный элемент в столбце и меняем строки местами
        for j in range(i+1, n):
            if abs(A[j][i]) > abs(A[max_index][i]):
                max_index = j
        A[[i, max_index]] = A[[max_index, i]]
        b[[i, max_index]] = b[[max_index, i]]
        
        # Выполняем преобразования строк
        for j in range(i+1, n):
            factor = A[j][i] / A[i][i] # На что нужно умножить стороку, чтобы обнулить элемент
            b[j] -= factor * b[i] # Вычитание для обнуления элементов под диагональю в столбце i
            A[j] -= factor * A[i] 
    
    # Нахожление решения
    x = np.zeros(n)
    for i in range(n-1, -1, -1):  # Решение вычисляется, начиная с последнего уравнения системы и пошагово обратно.
        x[i] = (b[i] - np.dot(A[i][i+1:], x[i+1:])) / A[i][i] # Bычисляет i-ый компонент вектора решения, используя ранее найденные значения x.
    return x

def gauss_seidel(A, b, x0=None, eps=1e-4, max_iter=1000):
    # Преобразую входные данные в тип float для точности вычислений
    A = A.astype(float)
    b = b.astype(float)
    
    n = len(b)

    # Если x0 не было предоставлено (равно None), то устанавливается вектор нулей размерности n. 
    # В противном случае, если x0 предоставлено, оно преобразуется в тип данных float.
    if x0 is None:
        x0 = np.zeros(n)
    else:
        x0 = x0.astype(float)


    for _ in range(max_iter):
        # Создается копия текущего приближенного решения x0 и сохраняется в x_old. 
        # Это нужно для последующего сравнения с новым приближением на шаге проверки сходимости.
        x_old = np.copy(x0)
        # Вложенный цикл обновляет каждую компоненту вектора x0 в соответствии с формулой метода Гаусса-Зейделя.
        for i in range(n):
            x0[i] = b[i]
            # Обновление x0[i] путем вычитания суммы произведений элементов матрицы A 
            # и соответствующих компонент предыдущего приближения x0 (кроме того, где j равно i).
            for j in range(n):
                if j != i:
                    x0[i] -= A[i][j] * x0[j]

            # Деление на диагональный элемент матрицы A[i][i].
            x0[i] /= A[i][i]
        # проверяю сходимость
        # разность между текущим приближением x0 и предыдущим приближением x_old должна быть < eps
        if np.linalg.norm(x0 - x_old) < eps: # Евклидова норма разницы
            return x0
    
    return x0


# Пример
n = int(input("Введите размер матрицы: "))
A = np.random.randint(1, 10, size=(n, n))
b = np.random.randint(1, 10, size=n)
np.fill_diagonal(A, np.sum(np.abs(A), axis=1) + 1) # Каждый элемент на диагонали будет равен сумме абсолютных значений элементов соответствующей строки плюс 1.
x0 = np.zeros(n) 

print("Матрица A:")
print(A)
print("Вектор b:")
print(b) 
print()
print()

# Решение методом Гаусса
x_gauss = gaussian(A, b)
print("Решение методом Гаусса:")
print(x_gauss)
print()

# Решение методом Гаусса-Зейделя
z = gauss_seidel(A, b, x0)
print("Решение методом Гаусса-Зейделя:")
print(z)

Матрица A:
[[14  3  3]
 [ 6 21  9]
 [ 5  8 23]]
Вектор b:
[8 2 5]


Решение методом Гаусса:
[ 0.56900452 -0.12631976  0.13763198]

Решение методом Гаусса-Зейделя:
[ 0.5690031  -0.12632229  0.13763317]
