In [4]:
import numpy as np

def gaussian(A, b):
    A = A.astype(float)
    b = b.astype(float)
    
    n = len(b)
    for i in range(n):
        max_index = i
        for j in range(i+1, n):
            if abs(A[j][i]) > abs(A[max_index][i]):
                max_index = j
        A[[i, max_index]] = A[[max_index, i]]
        b[[i, max_index]] = b[[max_index, i]]
        
        for j in range(i+1, n):
            factor = A[j][i] / A[i][i]
            b[j] -= factor * b[i]
            A[j] -= factor * A[i]
    
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A[i][i+1:], x[i+1:])) / A[i][i]
    return x


def gauss_seidel(A, b, x0, eps=1e-4, max_iter=1000):
    A = A.astype(float)
    b = b.astype(float)
    
    n = len(b)
    z = x0.astype(float)
    
    for _ in range(max_iter):
        x_old = np.copy(z)
        for i in range(n):
            z[i] = b[i]
            for j in range(n):
                if j != i:
                    z[i] -= A[i][j] * z[j]
            z[i] /= A[i][i]
        
        if np.linalg.norm(z - x_old) < eps:
            return z
    
    return z

# Пример
# Создание случайной матрицы A и вектора b
n = int(input("Введите размер матрицы: "))
A = np.random.randint(1, 10, size=(n, n))
b = np.random.randint(1, 10, size=n)
# Усиление диагонали матрицы A
np.fill_diagonal(A, np.sum(np.abs(A), axis=1) + 1)
x0 = np.zeros(3)

print("Матрица A:")
print(A)
print("Вектор b:")
print(b)

# Решение методом Гаусса
x_gauss = gaussian(A.copy(), b.copy())
print("Решение методом Гаусса:")
print(x_gauss)

# Решение методом Гаусса-Зейделя
z = gauss_seidel(A, b, x0)
print("Решение методом Гаусса-Зейделя:")
print(z)


def tikhonov(A, b, alpha):
    n = A.shape[1]
    regularizer = np.identity(n) * alpha  # Регуляризационная матрица

    A_transpose = A.T
    A_TA = np.dot(A_transpose, A)
    A_Tb = np.dot(A_transpose, b)

    t = np.linalg.solve(A_TA + regularizer, A_Tb)
    return t

# Устанавливаем коэффициент регуляризации
alpha = 0.1

# Получаем решение с использованием метода Тихонова
solution = tikhonov(A, b, alpha)
print("Решение методом Тихонова:")
print(solution)



Матрица A:
[[20  7  7]
 [ 8 17  4]
 [ 6  7 20]]
Вектор b:
[4 2 6]
Решение методом Гаусса:
[0.10471204 0.00563834 0.26661297]
Решение методом Гаусса-Зейделя:
[0.1046963  0.00564268 0.26661617]
Решение методом Тихонова:
[0.10469917 0.00570438 0.26652724]
